[package]
name = "abxtest"
version = "0.1.0"
authors = ["dork <dorknexus@github>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
rand = "0.7.3"
